# Generated by Django 4.2.14 on 2024-08-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_login_require'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
